### ISSUE TITLE
.fit_btn link on videos need "completeness" and other statuses

### ISSUE THREAD

**Issue by willdayble** [fitzroyacademy/web-app#100]
### Segment statuses

These are changed through student interaction, and indicate progress:

* Untouched (not started or looked at in any way)
* Touched (started but not completed)
* Active (current item)
* Complete

The untouched and touched states are not shown to the student, but are used by teachers and admins.

*Completeness* is set by a % watched on a segment by segment basis.

**Comment by Yuffster** [comment]
The new code will let us do this in the templates with:

```
<a class="fit_btn {{ segment.type }} {{ segment.user_status(current_user) }}">
```

This is hard-coded to output:

* complete if progress > 90
* touched if progress > 10
* untouched otherwise

These numbers can be easily tweaked.

Active is its own special class, since a user might be rewatching a previously completed video.

There was no 'touched' styling that I could find, so I made it an air freshener.  You'll probably want to change this.
