### ISSUE TITLE
User Preference Toggles

### ISSUE THREAD

**Issue by Yuffster** [fitzroyacademy/web-app#32]
We have a bunch of toggles like this that we need to hook into the database.

![](https://user-images.githubusercontent.com/13204/60375572-dc9ff680-99d7-11e9-8a33-c92c01ed8b3a.png)

This is probably best done as some sort of enum for the preference keys and then a join on the user_id with the boolean values returned through some helper method on the User model.

**Comment by willdayble** [comment]
Update to this: Can we please add a helper of some kind so that Will can add more "remember this about the user" toggles? 

**Importantly:** This will need to work without a page refresh, for things like "The user has changed their preference for which tabs are open and closed", or similar display things.
